=== silviagreen/Telesweaver/trunk/codice/xml/storie.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.w3.org/1999/XSL/Transform" xmlns="http://www.w3.org/1999/XSL/Transform" elementFormDefault="qualified">
<xs:element name="storie" type="Tstorie"/>
<xs: complexType name="Tstorie">
	<xs:sequence>
		<xs:element name="storia" type="Tstoria"/>	
	</xs:sequence>
</xs:complexType>
	
	<xs:complexType name="Tstoria">
		<xs:sequence>
			<xs:element name="titolo" type="xs:string"/>
			<xs:element name="autore" type="xs:string" nillable="true"/>
			<xs:element name="descrizione" type="xs:string"/>
			<xs:element name="incipit" type="xs:string"/>
			<xs:element name="stanza" type="Tstanza" maxOccurs="unbounded"/>
			<xs:element name="valutazione" type="Tvalutazione" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="recensione" type="Trecensione" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="ID" type="xs:positiveInteger" use="required"/>
	</xs:complexType>
	<xs:complexType name="Tstanza">
		<xs:sequence>
			<xs:element name="testoIniziale" type="xs:string" minOccurs="0"/>
			<xs:element name="oggettiContenuti" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="direzione" type="Tdirezione"/>
			<xs:element name="azione" type="Tazione"/>
		</xs:sequence>
		<xs:attribute name="inizio" type="xs:boolean" default="false"/>
		<xs:attribute name="ID" type="xs:positiveInteger" use="required"/>
		<xs:attribute name="fine" type="xs:boolean" default="false" use="required"/>
		<xs:attribute name="nome" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="Tdirezione">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="nord" type="xs:positiveInteger"/>
			<xs:element name="sud" type="xs:positiveInteger"/>
			<xs:element name="ovest" type="xs:positiveInteger"/>
			<xs:element name="est" type="xs:positiveInteger"/>
			<xs:element name="sopra" type="xs:positiveInteger"/>
			<xs:element name="sotto" type="xs:positiveInteger"/>
		</xs:choice>
		<xs:sequence>
			<xs:element name="testoRisposta" type="xsd:string" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="oggettoNecessario" type="xs:string"/>
		<xs:attribute name="stanzaDestinazione" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="Tvalutazione">
		<xs:sequence>
			<xs:element name="numero" type="xs:positiveInteger"/>
			<xs:element name="utente" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Trecensione">
		<xs:sequence>
			<xs:element name="testo" type="xs:string"/>
			<xs:element name="utente" type="xs:string"/>
			<xs:element name="data" type="dateTime"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Tazione">
		<xs:all>
			<xs:element name="sbloccataDa" type="xs:positiveInteger" minOccurs="0" maxOccurs="1" />
			<xs:element name="verbo" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
			<xs:element name="oggetto" type="xs:string" minOccurs="0"/>
			<xs:element name="secondoOggetto" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="testoRisposta" type="xs:string" />
			<xs:element name="oggettoOttenuto" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="sblocca" type="xs:positiveInteger" minOccurs="0" maxOccurs="unbounded" />
		</xs:all>
		<xs:attribute name="ID" type="xs:positiveInteger" use="required"/>
	</xs:complexType>
</xs:schema>

=== silviagreen/Telesweaver/trunk/codice/xml/storie.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xslt/avventure.xsl"?>
<storie xmlns="http://www.storie.com" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="http://www.storie.com storie.xsd">
	<storia id="1">
		<titolo>L'anello</titolo>
		<autore>Anonimo</autore>
		<descrizione>Un'avventura ricca di mistero. Aiuta l'ispettore Carnacky a risolvere il mistero di villa Anderson...Circola voce che in quella villa accadano strane cose la notte. Nel villaggio si pensa che la casa sia infestata da qualche spirito oscuro. Da quando si è sparsa la voce nessuno vuole più far visita alla famiglia Anderson per paura di venire aggredita dallo spirito oscuro. Per questo motivo la famiglia ha convocato il detective Carnacky. Ce la farai assumendo le vesti dell'investigatore dell'occulto a liberare la famiglia da questo spirito e farle riavere una vita normale?</descrizione>
		<incipit>Sei, ora, il detective dell'occulto Carnacky. Sei stato contattato dal sig. Anderson per un caso di 'infestazione'. Nella sua casa avvenivano strane cose: nel cuore di ogni notte la porta di una camera, da lui chiamata 'Camera Grigia', si apriva e sbatteva violentemente nonostante essa fosse chiusa a chiave e la chiave custodita in portineria.
			Ti trovi ora a Cheyne Walk, di fronte a casa Anderson per risolvere il caso...</incipit>
		<stanza id="1" inizio="true" fine="false" nome="giardino">
			<testoIniziale>Casa Anderson è una bella casa in stile vittoriano a due piani. Una torre ottogonale svetta al lato est della casa mentre una serie di tetti a spioventi a varie falde ricopre la casa. I muri in mattone sono ricoperti da edera rampicante. Puoi notare a Nord un vialetto di ingresso che conduce ad un portico in legno.
</testoIniziale>
			<direzioni>
				<direzione>
					<nome>nord</nome>
					<stanzaDestinazione>2</stanzaDestinazione>
				</direzione>
			</direzioni>
			<azione id="10">
				<verbo>entra</verbo>
				<oggetto>auto</oggetto>
				<sbloccataDa>9</sbloccataDa>
				<testoFallimento>Non ha senso prendere l'auto. È piena notte e la porta della camera grigia sta sbattendo.Devi rientrare in casa e risolvere il mistero...</testoFallimento>
				<testoRisposta>Sei entrato nella Bentley.</testoRisposta>
				<sblocca>11</sblocca>
			</azione>
			<azione id="11">
				<verbo>accendi</verbo>
				<oggetto>auto</oggetto>
				<sbloccataDa>10</sbloccataDa>
				<testoFallimento>Non puoi mettere in moto l'auto se devi ancora entrarci dentro!</testoFallimento>
				<testoRisposta>La tua Bentley si mette in moto.</testoRisposta>
			</azione>
			<azione id="35">
				<verbo>esci</verbo>
				<oggetto>auto</oggetto>
				<testoRisposta>Sei uscito dalla Bentley.</testoRisposta>
			</azione>
		</stanza>
		<stanza id="2" nome="portico">
			<testoIniziale>Il portico di casa Anderson è realizzato completamente in legno ed è ricoperto da edera rampicante. A nord la porta che conduce in casa. A fianco della porta puoi vedere il campanello.
</testoIniziale>
			<direzioni>
				<direzione>
					<nome>nord</nome>
					<oggettoNecessario>apriporta</oggettoNecessario>
					<testoFallimento>La porta è chiusa a chiave.</testoFallimento>
					<stanzaDestinazione>3</stanzaDestinazione>
				</direzione>
				<direzione>
					<nome>sud</nome>
					<oggettoNecessario>riposo</oggettoNecessario>
					<testoFallimento>Hai proprio bisogno di riposare.</testoFallimento>
					<stanzaDestinazione>1</stanzaDestinazione>
				</direzione>
			</direzioni>
			<azione id="1">
				<verbo>suona</verbo>
				<oggetto>campanello</oggetto>
				<oggettoOttenuto>apriporta</oggettoOttenuto>
				<testoRisposta>Il maggiordomo di casa Anderson ti viene ad aprire.
" Buonasera signor Carnacky, la stavo attendendo."
</testoRisposta>
				<sblocca>2</sblocca>
			</azione>
		</stanza>
		<stanza id="3" nome="soggiorno">
			<testoIniziale>Soggiorno di casa Anderson. Ci sono un tavolo, delle sedie, una dispensa e una libreria a muro. Puoi notare una rampa di scale che sale verso l'alto, a est la porta della stanza del maggiordomo mentre a ovest passando sotto un architrave puoi entrare nello studio del signor Anderson.
Il maggiordomo ti accompagna dentro.
</testoIniziale>
			<azione id="2">
				<sbloccataDa>1</sbloccataDa>
				<verbo>chiedi</verbo>
				<verbo>domanda</verbo>
				<verbo>interroga</verbo>
				<verbo>parla</verbo>
				<oggetto>maggiordomo</oggetto>
				<secondoOggetto>infestazione</secondoOggetto>
				<testoRisposta>
					" Tutte le notti verso mezzanotte la porta della camera grigia inizia a sbattere anche se la porta è chiusa a chiave e la chiave si trova in portineria. Si dice che parecchi anni fa, quando già si l'infestazione avveniva, vi furono strangolate la moglie e la figlia di un avo del signor Anderson che malauguratamente decisero di trascorrere la notte nella stanza. 
«Da allora nessuno ha più osato metter piede di notte nella stanza... Io stesso vi entro solo di giorno...
«Comunque vista l'ora le consiglio di andare a dormire nella camera degli ospiti, potrà iniziare le indagini domani. "
				</testoRisposta>
				<testoFallimento>Il maggiordomo non ti capisce.</testoFallimento>
			</azione>
			<azione id="51">
				<verbo>chiedi</verbo>
				<verbo>domanda</verbo>
				<verbo>interroga</verbo>
				<verbo>parla</verbo>
				<oggetto>maggiordomo</oggetto>
				<secondoOggetto>teca</secondoOggetto>
				<oggettoOttenuto>chiave</oggettoOttenuto>
				<testoRisposta>La teca appartiene alla famiglia Anderson. Ma forse ho con me qualcosa con me per aprirla. Eccole la chiave per aprire la teca.</testoRisposta>
				<sblocca>52</sblocca>
			</azione>
			<direzioni>
				<direzione>
					<nome>sopra</nome>
					<stanzaDestinazione>4</stanzaDestinazione>
				</direzione>
				<direzione>
					<nome>sud</nome>
					<stanzaDestinazione>2</stanzaDestinazione>
				</direzione>
			</direzioni>
		</stanza>
		<stanza id="4" nome="corridoio">
			<testoIniziale>È il corridoio del piano superiore di casa Anderson. Ai muri sono appesi dei quadri che ritraggono avi della dinastia Anderson. A est puoi vedere la porta della camera grigia, a nord la porta della camera degli ospiti, a ovest la porta del bagno, verso il basso vi è una rampa di scale che porta nel soggiorno.
</testoIniziale>
			<direzioni>
				<direzione>
					<nome>sotto</nome>
					<oggettoNecessario>riposo</oggettoNecessario>
					<testoFallimento>Hai proprio bisogno di riposare.</testoFallimento>
					<stanzaDestinazione>3</stanzaDestinazione>
				</direzione>
				<direzione>
					<nome>nord</nome>
					<oggettoNecessario>entraospiti</oggettoNecessario>
					<testoFallimento>come puoi entrare nella stanza se non l'hai aperta?</testoFallimento>
					<stanzaDestinazione>5</stanzaDestinazione>
				</direzione>
				<direzione>
					<nome>ovest</nome>
					<stanzaDestinazione>6</stanzaDestinazione>
				</direzione>
				<direzione>
					<nome>est</nome>
					<oggettoNecessario>aspetta</oggettoNecessario>
					<testoFallimento>La porta è chiusa a chiave!</testoFallimento>
					<testoRisposta>Appena ti avvicini alla porta della camera grigia una forza oscura ti afferra per il braccio...
</testoRisposta>
				</direzione>
				<direzione>
					<nome>sopra</nome>
					<oggettoNecessario>vialibera</oggettoNecessario>
					<stanzaDestinazione>13</stanzaDestinazione>
				</direzione>
			</direzioni>
			<azione id="3">
				<verbo>apri</verbo>
				<oggetto>porta</oggetto>
				<secondoOggetto>ospiti</secondoOggetto>
				<testoRisposta>Entra pure.</testoRisposta>
				<oggettoOttenuto>entraospiti</oggettoOttenuto>
				<sbloccs>4</sbloccs>
			</azione>
			<azione id="8">
				<verbo>aspetta</verbo>
				<sbloccataDa>7</sbloccataDa>
				<testoRisposta>Il tempo passa.
Una forza oscura ti sta tirando per il braccio. Vuole trascinarti dentro la camera grigia. Stai cercando di resistere e di tirarti indietro ma la forza è troppo forte.
Se non fai qualcosa nel giro di pochi secondi sarai morto. </testoRisposta>
				<sblocca>9</sblocca>
			</azione>
			<azione id="9">
				<verbo>urla</verbo>
				<sbloccataDa>8</sbloccataDa>
				<testoRisposta>Non appena sente le tue grida, il maggiordomo sale in corridoio e con un enorme sforzo ti tira indietro liberandoti dalla morsa della forza. In uno stato di semiincoscienza ti riporta nella camera degli ospiti.Oramai si è fatta l'alba e la porta ha smesso di sbattere. Non vi è più pericolo. Ora, per affrontare il mistero della camera grigia devi andare a casa tua a recuperare tutto il materiale necessario...
</testoRisposta>
				<sblocca>10</sblocca>
			</azione>
			<azione id="36">
				<verbo>apri</verbo>
				<oggetto>porta</oggetto>
				<secondoOggetto>grigia</secondoOggetto>
				<oggettoOttenuto>vialibera</oggettoOttenuto>
				<testoRisposta>Hai aperto la porta. Ora, salendo le scale puoi accedere alla camera grigia.</testoRisposta>
			</azione>
		</stanza>
		<stanza id="6" nome="bagno">
			<testoIniziale>È il bagno di casa Anderson. Puoi vedere uno specchio, un lavandino, un bidet e una toilette.</testoIniziale>
			<direzioni>
				<direzione>
					<nome>est</nome>
					<stanzaDestinazione>4</stanzaDestinazione>
				</direzione>
			</direzioni>
		</stanza>
		<stanza id="7" nome="camera degli ospiti">
			<testoIniziale>Sei nella camera degli ospiti della signora Anderson. La camera da letto degli ospiti della casa Anderson è arredata con un letto, un comodino, un armadio e un quadro che raffigura uno degli avi del signor Anderson. A sud puoi vedere la porta che conduce nel corridoio.
</testoIniziale>
			<direzioni>
				<direzione>
					<nome>sud</nome>
					<oggettoNecessario>riposo</oggettoNecessario>
					<testoFallimento>Hai proprio bisogno di riposare.</testoFallimento>
					<stanzaDestinazione>4</stanzaDestinazione>
				</direzione>
			</direzioni>
			<azione id="4">
				<verbo>entra</verbo>
				<oggetto>letto</oggetto>
				<testoRisposta>Ti trovi dentro il letto.</testoRisposta>
				<sbloccataDa>3</sbloccataDa>
				<sblocca>5</sblocca>
			</azione>
			<azione id="5">
